# encapsulate all of the repeated init operations into a single layer
FROM node:lts-alpine
WORKDIR /app

RUN corepack enable
RUN yarn set version berry

ADD package.json yarn.lock ./
RUN yarn install

ADD ./postcss.config.js ./drizzle.config.ts ./tailwind.config.ts ./tsconfig.json ./vite.config.ts ./

ENV VITE_DB_FILE_NAME='file:./db/db.sqlite'

CMD ["yarn", "dev", "--host"]

EXPOSE 5173
